"""added processing_error column

Revision ID: feff0659442f
Revises: 6ad03784b4b9
Create Date: 2026-07-06 14:56:57.577597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feff0659442f'
down_revision: Union[str, Sequence[str], None] = '6ad03784b4b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('processing_error', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'jobs', ['text'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='unique')
    op.drop_column('jobs', 'processing_error')
    # ### end Alembic commands ###
